# permissions for end users to view hwameistorclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hwameistorcluster-viewer-role
rules:
- apiGroups:
  - hwameistor.io
  resources:
  - hwameistorclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hwameistor.io
  resources:
  - hwameistorclusters/status
  verbs:
  - get
