
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - hwameistor.io
  resources:
  - clusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hwameistor.io
  resources:
  - clusters/finalizers
  verbs:
  - update
- apiGroups:
  - hwameistor.io
  resources:
  - clusters/status
  verbs:
  - get
  - patch
  - update
