apiVersion: hwameistor.io/v1alpha1
kind: Cluster
metadata:
  name: hwameistor-cluster
spec:
  diskReserveConfigurations:
  {{- range $.Values.diskReserve }}
  - nodeName: {{ .nodeName }}
    devices:
    {{- range .devices }}
    - {{ . }}
    {{- end }}
  {{- end }}
  notClaimDisk: {{ $.Values.global.notClaimDisk }}
  targetNamespace: {{ $.Values.global.targetNamespace }}
  rbac:
    serviceAccountName: "hwameistor-admin"
  localDiskManager:
    kubeletRootDir: {{ $.Values.localDiskManager.kubeletRootDir | quote }}
    csi:
      registrar:
        image:
          registry: {{ $.Values.global.k8sImageRegistry }}
          repository: {{ $.Values.localDiskManager.csi.registrar.imageRepository }}
          tag: {{ $.Values.localDiskManager.csi.registrar.tag }}
      controller:
        replicas: {{ $.Values.localDiskManager.csi.controller.replicas }}
        provisioner:
          image:
            registry: {{ $.Values.global.k8sImageRegistry }}
            repository: {{ $.Values.localDiskManager.csi.provisioner.imageRepository }}
            tag: {{ $.Values.localDiskManager.csi.provisioner.tag }}
        attacher:
          image:
            registry: {{ $.Values.global.k8sImageRegistry }}
            repository: {{ $.Values.localDiskManager.csi.attacher.imageRepository }}
            tag: {{ $.Values.localDiskManager.csi.attacher.tag }}
    manager:
      image:
        registry: {{ $.Values.global.hwameistorImageRegistry }}
        repository: {{ $.Values.localDiskManager.manager.imageRepository }}
        tag: {{ template "hwameistor.localDiskManagerImageTag" . }}
    tolerationOnMaster: {{ $.Values.localDiskManager.tolerationOnMaster }}
  localStorage:
    disable: {{ $.Values.localStorage.disable }}
    kubeletRootDir: {{ $.Values.localStorage.kubeletRootDir | quote }}
    csi:
      registrar:
        image:
          registry: {{ $.Values.global.k8sImageRegistry }}
          repository: {{ $.Values.localStorage.csi.registrar.imageRepository }}
          tag: {{ $.Values.localStorage.csi.registrar.tag }}
      controller:
        replicas: {{ $.Values.localStorage.csi.controller.replicas }}
        provisioner:
          image:
            registry: {{ $.Values.global.k8sImageRegistry }}
            repository: {{ $.Values.localStorage.csi.provisioner.imageRepository }}
            tag: {{ $.Values.localStorage.csi.provisioner.tag }}
        attacher:
          image:
            registry: {{ $.Values.global.k8sImageRegistry }}
            repository: {{ $.Values.localStorage.csi.attacher.imageRepository }}
            tag: {{ $.Values.localStorage.csi.attacher.tag }}
        resizer:
          image:
            registry: {{ $.Values.global.k8sImageRegistry }}
            repository: {{ $.Values.localStorage.csi.resizer.imageRepository }}
            tag: {{ $.Values.localStorage.csi.resizer.tag }}
        monitor:
          image:
            registry: {{ $.Values.global.k8sImageRegistry }}
            repository: {{ $.Values.localStorage.csi.monitor.imageRepository }}
            tag: {{ $.Values.localStorage.csi.monitor.tag }}
        snapshotController:
          image:
            registry: {{ $.Values.global.k8sImageRegistry }}
            repository: {{ $.Values.localStorage.csi.snapshotController.imageRepository }}
            tag: {{ $.Values.localStorage.csi.snapshotController.tag }}
        snapshotter:
          image:
            registry: {{ $.Values.global.k8sImageRegistry }}
            repository: {{ $.Values.localStorage.csi.snapshotter.imageRepository }}
            tag: {{ $.Values.localStorage.csi.snapshotter.tag }}
    member:
      image:
        registry: {{ $.Values.global.hwameistorImageRegistry }}
        repository: {{ $.Values.localStorage.member.imageRepository }}
        tag: {{ template "hwameistor.localStorageImageTag" . }}
      rcloneImage:
        repository: {{ $.Values.localStorage.migrate.rclone.imageRepository }}
        tag: {{ $.Values.localStorage.migrate.rclone.tag }}
      hostPathSSHDir: {{ $.Values.localStorage.member.hostPathSSHDir }}
      hostPathDRBDDir: {{ $.Values.localStorage.member.hostPathDRBDDir }}
    tolerationOnMaster: {{ $.Values.localStorage.tolerationOnMaster }}
  scheduler:
    disable: {{ $.Values.scheduler.disable }}
    replicas: {{ $.Values.scheduler.replicas }}
    scheduler:
      image:
        registry: {{ $.Values.global.hwameistorImageRegistry }}
        repository: {{ $.Values.scheduler.imageRepository }}
        tag: {{ template "hwameistor.schedulerImageTag" . }}
  admissionController:
    disable: {{ $.Values.admission.disable }}
    replicas: {{ $.Values.admission.replicas }}
    controller:
      image:
        registry: {{ $.Values.global.hwameistorImageRegistry }}
        repository: {{ $.Values.admission.imageRepository }}
        tag: {{ template "hwameistor.admissionImageTag" . }}
  evictor:
    disable: {{ $.Values.evictor.disable }}
    replicas: {{ $.Values.evictor.replicas }}
    evictor:
      image:
        registry: {{ $.Values.global.hwameistorImageRegistry }}
        repository: {{ $.Values.evictor.imageRepository }}
        tag: {{ template "hwameistor.evictorImageTag" . }}
  apiServer:
    disable: {{ $.Values.apiserver.disable }}
    replicas: {{ $.Values.apiserver.replicas }}
    server:
      image:
        registry: {{ $.Values.global.hwameistorImageRegistry }}
        repository: {{ $.Values.apiserver.imageRepository }}
        tag: {{ template "hwameistor.apiserverImageTag" . }}
    authentication:
      enable: {{ $.Values.apiserver.authentication.enable }}
      accessId: {{ $.Values.apiserver.authentication.accessId }}
      secretKey: {{ $.Values.apiserver.authentication.secretKey }}
  exporter:
    disable: {{ $.Values.exporter.disable }}
    replicas: {{ $.Values.exporter.replicas }}
    collector:
      image:
        registry: {{ $.Values.global.hwameistorImageRegistry }}
        repository: {{ $.Values.exporter.imageRepository }}
        tag: {{ template "hwameistor.exporterImageTag" . }}
  auditor:
    disable: {{ $.Values.auditor.disable }}
    replicas: {{ $.Values.auditor.replicas }}
    auditor:
      image:
        registry: {{ $.Values.global.hwameistorImageRegistry }}
        repository: {{ $.Values.auditor.imageRepository }}
        tag: {{ template "hwameistor.exporterImageTag" . }}
  failoverAssistant:
    disable: {{ $.Values.failoverAssistant.disable }}
    replicas: {{ $.Values.failoverAssistant.replicas }}
    assistant:
      image:
        registry: {{ $.Values.global.hwameistorImageRegistry }}
        repository: {{ $.Values.failoverAssistant.imageRepository }}
        tag: {{ template "hwameistor.failoverAssistantImageTag" . }}
  pvcAutoResizer:
    disable: {{ $.Values.pvcAutoResizer.disable }}
    replicas: {{ $.Values.pvcAutoResizer.replicas }}
    autoresizer:
      image:
        registry: {{ $.Values.global.hwameistorImageRegistry }}
        repository: {{ $.Values.pvcAutoResizer.imageRepository }}
        tag: {{ template "hwameistor.pvcAutoResizerImageTag" . }}
  localDiskActionController:
    disable: {{ $.Values.localDiskActionController.disable }}
    replicas: {{ $.Values.localDiskActionController.replicas }}
    controller:
      image:
        registry: {{ $.Values.global.hwameistorImageRegistry }}
        repository: {{ $.Values.localDiskActionController.imageRepository }}
        tag: {{ template "hwameistor.localDiskActionControllerImageTag" . }}
  ui:
    disable: {{ $.Values.ui.disable }}
    replicas: {{ $.Values.ui.replicas }}
    ui:
      image:
        registry: {{ $.Values.global.hwameistorImageRegistry }}
        repository: {{ $.Values.ui.imageRepository }}
        tag: {{ template "hwameistor.uiImageTag" . }}
  drbd:
    {{- if .Values.ha.disable }}
    disable: true
    {{- end }}
    deployOnMaster: {{ $.Values.ha.deployOnMaster | quote }}
    imageRegistry: {{ $.Values.global.hwameistorImageRegistry }}
    # imageRepoOwner: "hwameistor"
    imageRepoOwner: {{ $.Values.ha.imageRepoOwner }}
    imagePullPolicy: "IfNotPresent"
    # drbdVersion: "v9.0.32-1"
    drbdVersion: {{ $.Values.ha.drbdVersion }}
    upgrade: "no"
    checkHostName: "yes"
    useAffinity: "no"
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/master
            operator: DoesNotExist
          - key: node-role.kubernetes.io/control-plane
            operator: DoesNotExist
    chartVersion: "v0.3.6"
  storageClass:
    allowVolumeExpansion: true
    reclaimPolicy: "Delete"
    fsType: "xfs"