global:
  targetNamespace: hwameistor
  hwameistorImageRegistry: ghcr.io
  #hwameistorImageRegistry: ghcr.m.daocloud.io
  k8sImageRegistry: registry.k8s.io
  # k8sImageRegistry: m.daocloud.io/registry.k8s.io
  hwameistorVersion: v0.9.3

operator:
  replicas: 1
  imageRepository: hwameistor/operator
  tag: v0.9.6
 
localDiskManager:
  tolerationOnMaster: true
  kubeletRootDir: /var/lib/kubelet
  manager:
    imageRepository: hwameistor/local-disk-manager
    tag: v0.9.3
  csi:
    registrar:
      imageRepository: sig-storage/csi-node-driver-registrar
      tag: v2.5.0
    controller:
      replicas: 1
    provisioner:
      imageRepository: sig-storage/csi-provisioner
      tag: v2.0.3
    attacher:
      imageRepository: sig-storage/csi-attacher
      tag: v3.0.1

localStorage:
  tolerationOnMaster: true
  kubeletRootDir: /var/lib/kubelet
  member:
    imageRepository: hwameistor/local-storage
    tag: v0.9.3
  csi:
    registrar:
      imageRepository: sig-storage/csi-node-driver-registrar
      tag: v2.5.0
    controller:
      replicas: 1
    provisioner:
      imageRepository: sig-storage/csi-provisioner
      tag: v2.0.3
    attacher:
      imageRepository: sig-storage/csi-attacher
      tag: v3.0.1
    resizer:
      imageRepository: sig-storage/csi-resizer
      tag: v1.0.1
    monitor:
      imageRepository: sig-storage/csi-external-health-monitor-controller
      tag: v0.8.0
  migrate:
    rclone:
      imageRepository: rclone/rclone
      tag: 1.53.2

scheduler:
  replicas: 1
  imageRepository: hwameistor/scheduler
  tag: v0.9.3

admission:
  replicas: 1
  imageRepository: hwameistor/admission
  tag: v0.9.3

evictor:
  replicas: 1
  imageRepository: hwameistor/evictor
  tag: v0.9.3

apiserver:
  replicas: 1
  imageRepository: hwameistor/apiserver
  tag: v0.9.3

exporter:
  replicas: 1
  imageRepository: hwameistor/exporter
  tag: v0.9.3

ui:
  replicas: 1
  imageRepository: hwameistor/hwameistor-ui
  tag: v0.9.3

ha:
  module: drbd
  deployOnMaster: "yes"
  imageRepoOwner: hwameistor
  drbdVersion: v9.0.32-1