global:
  targetNamespace: hwameistor
  notClaimDisk: false
  hwameistorImageRegistry: ghcr.io
  #hwameistorImageRegistry: ghcr.m.daocloud.io
  k8sImageRegistry: registry.k8s.io
  # k8sImageRegistry: m.daocloud.io/registry.k8s.io
  hwameistorVersion: v0.12.1

operator:
  replicas: 1
  imageRepository: hwameistor/operator
  tag: v0.10.8
 
localDiskManager:
  tolerationOnMaster: true
  kubeletRootDir: /var/lib/kubelet
  manager:
    imageRepository: hwameistor/local-disk-manager
    tag: v0.12.1
  csi:
    registrar:
      imageRepository: sig-storage/csi-node-driver-registrar
      tag: v2.5.0
    controller:
      replicas: 1
    provisioner:
      imageRepository: sig-storage/csi-provisioner
      tag: v2.0.3
    attacher:
      imageRepository: sig-storage/csi-attacher
      tag: v3.0.1

localStorage:
  disable: false
  tolerationOnMaster: true
  kubeletRootDir: /var/lib/kubelet
  member:
    imageRepository: hwameistor/local-storage
    tag: v0.12.1
  csi:
    registrar:
      imageRepository: sig-storage/csi-node-driver-registrar
      tag: v2.5.0
    controller:
      replicas: 1
    provisioner:
      imageRepository: sig-storage/csi-provisioner
      tag: v2.0.3
    attacher:
      imageRepository: sig-storage/csi-attacher
      tag: v3.0.1
    resizer:
      imageRepository: sig-storage/csi-resizer
      tag: v1.0.1
    monitor:
      imageRepository: sig-storage/csi-external-health-monitor-controller
      tag: v0.8.0
  migrate:
    rclone:
      imageRepository: rclone/rclone
      tag: 1.53.2

scheduler:
  disable: false
  replicas: 1
  imageRepository: hwameistor/scheduler
  tag: v0.12.1

admission:
  disable: false
  replicas: 1
  imageRepository: hwameistor/admission
  tag: v0.12.1

evictor:
  disable: false
  replicas: 1
  imageRepository: hwameistor/evictor
  tag: v0.12.1

apiserver:
  disable: false
  replicas: 1
  imageRepository: hwameistor/apiserver
  tag: v0.12.1
  authentication:
    enable: false
    accessId: admin
    secretKey: admin

exporter:
  disable: false
  replicas: 1
  imageRepository: hwameistor/exporter
  tag: v0.12.1

ui:
  disable: false
  replicas: 1
  imageRepository: hwameistor/hwameistor-ui
  tag: v0.12.1

ha:
  disable: false
  module: drbd
  deployOnMaster: "yes"
  imageRepoOwner: hwameistor
  drbdVersion: v9.0.32-1

# diskReserve example
# diskReserve: 
# - nodeName: node1
#   devices:
#   - /dev/sdc
#   - /dev/sdd
# - nodeName: node2
#   devices:
#   - /dev/sdc
#   - /dev/sde

# diskReserve example by json string
# diskReserve: [{"nodeName":"node1","devices":["/dev/sdc","/dev/sdc"]},{"nodeName":"node2","devices":["/dev/sdc","/dev/sde"]}]

# diskReserve example for helm install --set
# --set diskReserve\[0\].nodeName=node1 --set diskReserve\[0\].devices={/dev/sdc\,/dev/sdd} --set diskReserve\[1\].nodeName=node2 --set diskReserve\[1\].devices={/dev/sdc\,/dev/sde}

preHookJob:
  imageRepository: dtzar/helm-kubectl
  tag: 3.9