name: HwameiStor PR

on:
  pull_request:
    branches:
      - main
    paths:
      - "test/**"

jobs:
  pr-test:
    runs-on: ["vsphere"]
    timeout-minutes: 180
    steps:
      - name: delete
        run: |
          sudo rm -rf /github/actions-runner/_work/hwameistor/hwameistor/_build
          sudo rm -rf /github/actions-runner/_work/hwameistor/hwameistor/test/e2e/drbd-adapter/
          sudo rm -rf /home/github/actions-runner/_work/hwameistor/hwameistor/_build
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: pr test
        env:
          E2E_TESTING_LEVEL: "pr-e2e"
        run: make pr-test

